### ISSUE TITLE
user.get_live_info返回网络错误。状态码：412

### ISSUE THREAD

**Issue by a08381** [Passkou/bilibili_api#105]
测试用代码：
https://paste.ubuntu.com/p/gTj2mMjYcr/

```
(venv) PS D:\Download\Test> & d:/Download/Test/venv/Scripts/python.exe d:/Download/Test/biliapi_test.py

已扫描，等待确认
<bilibili_api.utils.Verify object at 0x000002A8D3F36940>
已确认，跳转登录
{'isLogin': True, 'email_verified': 1, 'face': 'http://i1.hdslb.com/bfs/face/9fcc1933dbf1fff553c524570741515ac6d59db3.jpg', 'level_info': {'current_level': 
5, 'current_min': 10800, 'current_exp': 24183, 'next_exp': 28800}, 'mid': 623906, 'mobile_verified': 1, 'money': 1536.9, 'moral': 78, 'official': {'role': 0, 'title': '', 'desc': '', 'type': -1}, 'officialVerify': {'type': -1, 'desc': ''}, 'pendant': {'pid': 0, 'name': '', 'image': '', 'expire': 0, 'image_enhance': '', 'image_enhance_frame': ''}, 'scores': 0, 'uname': '风之哀-Official-', 'vipDueDate': 1633190400000, 'vipStatus': 1, 'vipType': 2, 'vip_pay_type': 1, 'vip_theme_type': 0, 'vip_label': {'path': '', 'text': '年度大会员', 'label_theme': 'annual_vip'}, 'vip_avatar_subscript': 1, 'vip_nickname_color': '#FB7299', 'wallet': {'mid': 623906, 'bcoin_balance': 0, 'coupon_balance': 0, 'coupon_due_time': 0}, 'has_shop': False, 'shop_url': '', 'allowance_count': 0, 'answer_status': 0}
Traceback (most recent call last):
  File "d:/Download/Test/biliapi_test.py", line 126, in <module>
    asyncio.get_event_loop().run_until_complete(test())
  File "c:\users\administrator\.pyenv\pyenv-win\versions\3.8.6\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "d:/Download/Test/biliapi_test.py", line 122, in test
    print(user.get_live_info(uid=user_info["mid"], verify=verify))
  File "D:\Download\Test\venv\lib\site-packages\bilibili_api\user.py", line 101, in get_live_info
    data = utils.get(url=api["url"], params=params, cookies=verify.get_cookies())
  File "D:\Download\Test\venv\lib\site-packages\bilibili_api\utils.py", line 418, in get
    resp = request("GET", url=url, params=params, cookies=cookies, headers=headers, data_type=data_type, **kwargs)
  File "D:\Download\Test\venv\lib\site-packages\bilibili_api\utils.py", line 404, in request
    raise exceptions.NetworkException(req.status_code)
bilibili_api.exceptions.NetworkException: 网络错误。状态码：412
```

为了确认是不是网络问题把代码拿去服务器上跑了，结果如下

```
(venv-test) [root@iZuf6awprorqt69yjifap2Z test]# python biliapi_test.py
   
已扫描，等待确认
<bilibili_api.utils.Verify object at 0x7f03ea0f6ca0>
已确认，跳转登录
{'isLogin': True, 'email_verified': 1, 'face': 'http://i1.hdslb.com/bfs/face/9fcc1933dbf1fff553c524570741515ac6d59db3.jpg', 'level_info': {'current_level': 5, 'current_min': 10800, 'current_exp': 24183, 'next_exp': 28800}, 'mid': 623906, 'mobile_verified': 1, 'money': 1536.9, 'moral': 78, 'official': {'role': 0, 'title': '', 'desc': '', 'type': -1}, 'officialVerify': {'type': -1, 'desc': ''}, 'pendant': {'pid': 0, 'name': '', 'image': '', 'expire': 0, 'image_enhance': '', 'image_enhance_frame': ''}, 'scores': 0, 'uname': '风之哀-Official-', 'vipDueDate': 1633190400000, 'vipStatus': 1, 'vipType': 2, 'vip_pay_type': 1, 'vip_theme_type': 0, 'vip_label': {'path': '', 'text': '年度大会员', 'label_theme': 'annual_vip'}, 'vip_avatar_subscript': 1, 'vip_nickname_color': '#FB7299', 'wallet': {'mid': 623906, 'bcoin_balance': 0, 'coupon_balance': 0, 'coupon_due_time': 0}, 'has_shop': False, 'shop_url': '', 'allowance_count': 0, 'answer_status': 0}
Traceback (most recent call last):
  File "biliapi_test.py", line 126, in <module>
    asyncio.get_event_loop().run_until_complete(test())
  File "/root/.pyenv/versions/3.8.6/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "biliapi_test.py", line 122, in test
    print(user.get_live_info(uid=user_info["mid"], verify=verify))
  File "/root/.pyenv/versions/venv-test/lib/python3.8/site-packages/bilibili_api/user.py", line 101, in get_live_info
    data = utils.get(url=api["url"], params=params, cookies=verify.get_cookies())
  File "/root/.pyenv/versions/venv-test/lib/python3.8/site-packages/bilibili_api/utils.py", line 418, in get
    resp = request("GET", url=url, params=params, cookies=cookies, headers=headers, data_type=data_type, **kwargs)
  File "/root/.pyenv/versions/venv-test/lib/python3.8/site-packages/bilibili_api/utils.py", line 404, in request
    raise exceptions.NetworkException(req.status_code)
bilibili_api.exceptions.NetworkException: 网络错误。状态码：412
```

**Comment by a08381** [comment]
看到了#96，拿去服务器上跑了一下，结果也是412

**Comment by Passkou** [comment]
估计是反爬虫越来越严了，回头看看

**Comment by a08381** [comment]
> 估计是反爬虫越来越严了，回头看看

可能是这个API不让用了，我换了一个API获得了需要的信息。

```python
async def test():
    await run()
    if verify.check()["code"] == 0:
        uid = user.get_self_info(verify=verify)["mid"]
        user_info = user.get_user_info(uid=uid, verify=verify)
        live_room = user_info["live_room"]
        if live_room["roomStatus"] == 1:
            roomid = live_room["roomid"]
```

**Comment by a08381** [comment]
奇怪的是get_live_info和get_room_info在浏览器中访问是正常的，但是在库中不起作用。

**Comment by Passkou** [comment]
不是，我已经找到原因了，他把我设置默认的 UA 头给 ban 了。。。我服了，我从浏览器的 UA 头复制的啊。。

**Comment by a08381** [comment]
> 不是，我已经找到原因了，他把我设置默认的 UA 头给 ban 了。。。我服了，我从浏览器的 UA 头复制的啊。。

UA头可以自定义吗？

**Comment by Passkou** [comment]
尝试该版本：
`pip install bilibili-api==3.1.7b1`

**Comment by a08381** [comment]
我在想，是否可以通过给所有api添加** kwargs这个参数来实现自定义ua和referer的功能？

**Comment by Passkou** [comment]
没必要，我已经定义好的足够绕过检查了

**Comment by Passkou** [comment]
3.1.7 已解决
