### ISSUE TITLE
article.get_content() 获取特定专栏内容时返回异常

### ISSUE THREAD

**Issue by tianque1** [Passkou/bilibili_api#114]
类型：异常
版本：3.1.8
~~你这是什么API啊，害人不浅啊。你已经是个成熟的API了，怎么还不会帮我自动爬虫？我看你就是个逊啦。~~
```
from bilibili_api import *
article.get_content(cid=9478229)
```
异常为
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "E:\python3.9.1\lib\site-packages\bilibili_api\article.py", line 438, in get_content
    node_handle(p, para)
  File "E:\python3.9.1\lib\site-packages\bilibili_api\article.py", line 432, in node_handle
    node_handle(child, obj)
  File "E:\python3.9.1\lib\site-packages\bilibili_api\article.py", line 432, in node_handle
    node_handle(child, obj)
  File "E:\python3.9.1\lib\site-packages\bilibili_api\article.py", line 432, in node_handle
    node_handle(child, obj)
UnboundLocalError: local variable 'obj' referenced before assignment
```

**Comment by Passkou** [comment]
我康康

**Comment by Passkou** [comment]
尝试v3.2.1
`pip install bilibili-api==3.2.1`

**Comment by tianque1** [comment]
感谢！o(*￣▽￣*)ブ
