### ISSUE TITLE
How to use "get_history_danmaku"?

### ISSUE THREAD

**Issue by flowcut** [Passkou/bilibili_api#18]
I got the following error:

>>> danmuku = my_video.get_history_danmaku(date="2020-08-01", page=0)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\envs\pytorch\lib\site-packages\bilibili_api\src\video.py", line 119, in get_history_danmaku
    con = req.content.decode("utf-8")
  File "D:\Anaconda\envs\pytorch\lib\xml\dom\minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "D:\Anaconda\envs\pytorch\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "D:\Anaconda\envs\pytorch\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

**Comment by Passkou** [comment]
What's your version of this API and can you show your whole code?

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by flowcut** [comment]
The bilibili_api is at version 1.3.3
The code is as follows
>>> bvid = 'BV1sD4y1U7Ny'
>>> my_video = video.VideoInfo(bvid=bvid, verify=verify)
>>> danmaku = my_video.get_danmaku()
>>> danmaku = my_video.get_history_danmaku(date="2020-08-01", page=0)

**Comment by Passkou** [comment]
Maybe you should update the api. The latest api(V1.4.0) has fixed some bugs.
```python
from bilibili_api import video, Verify

verify = Verify("xxxxxxxxx")
bvid = 'BV1sD4y1U7Ny'
my_video = video.VideoInfo(bvid=bvid, verify=verify)
danmaku = my_video.get_history_danmaku(date="2020-08-01", page=0)
for dm in danmaku:
    print(dm)
```
OUTPUT:
```
2020-08-01 23:39:34, 0:00:00.940000, 爷青回！！！
2020-08-01 23:28:50, 0:00:00.940000, 恭喜你发现了宝藏
2020-08-01 23:28:35, 0:00:00.940000, 恭喜你发现宝藏！
2020-08-01 23:28:17, 0:00:00.940000, 恭喜你发现了宝藏
2020-08-01 23:21:04, 0:00:00.559000, 爷青回！
2020-08-01 23:10:20, 0:00:00.674000, 本期剧情爆炸，更有蕾式小剪
etc.
```

**Comment by flowcut** [comment]
Sorry for my late response.

I've updated the bilibili_api but the error is still there. I also tried updating the xml library but it didn't work either.

**Comment by Passkou** [comment]
What's your IDE you are using? You can use debug mode to see the raw content that bilibili returned.
Set some breakpoints around line 119 in module `video` or you can add some lines to print them.
