### ISSUE TITLE
很奇怪把video_info.get_playurl()放在video_info.get_video_info()后面就会报错

### ISSUE THREAD

**Issue by mz289** [Passkou/bilibili_api#3]
很奇怪把`video_info.get_playurl()`放在`video_info.get_video_info()`后面就会报错
```python
from bilibili_api import video
video_info = video.VideoInfo(44566179)
print(video_info.get_video_info())
print(video_info.get_playurl())
```
```
Traceback (most recent call last):
  File "./text1.py", line 6, in <module>
    print(video_info.get_playurl())
  File "/mnt/d/Code/bilibili_tool/.venv/lib/python3.6/site-packages/bilibili_api/src/video.py", line 174, in get_playurl
    if page + 1 > len(self.info["pages"]):
TypeError: 'Get' object is not subscriptable
```

**Comment by Passkou** [comment]
修了修了，少写了一对括号导致返回的是Get类而不是数据QAQ，继续升级一下就可以了

**Comment by mz289** [comment]
好了可以运行了👍👍👍
