### ISSUE TITLE
有些视频无法获取视频信息和下载链接

### ISSUE THREAD

**Issue by mz289** [Passkou/bilibili_api#4]
用大佬项目爬收藏夹的时候发现有一些视频无法获取下载链接
比如这个
https://www.bilibili.com/video/av413587
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/Code/bilibili_tool/.venv/lib/python3.6/site-packages/bilibili_api/src/video.py", line 173, in get_playurl
    self.__get_self_info()
  File "/mnt/d/Code/bilibili_tool/.venv/lib/python3.6/site-packages/bilibili_api/src/video.py", line 29, in __get_self_info
    self.info = self.get_video_info()
  File "/mnt/d/Code/bilibili_tool/.venv/lib/python3.6/site-packages/bilibili_api/src/video.py", line 40, in get_video_info
    self.info = get()
  File "/mnt/d/Code/bilibili_tool/.venv/lib/python3.6/site-packages/bilibili_api/src/utils.py", line 143, in __call__
    raise exception.BiliException(con["code"], con["message"])
bilibili_api.src.exception.BiliException: 返回code不为0。错误代码：-403, 信息：访问权限不足
```

**Comment by Passkou** [comment]
看这AV号是早期的视频了吧，可能当时这个API并没有启用，我试了你把get_video_info(is_simple=True)打开，这个就是用另外一个比较简单的信息的API了，可以用

**Comment by mz289** [comment]
我发现这个视频只有会员能观看没有播放量，不知道是不是这个的原因

**Comment by Passkou** [comment]
确实有部分视频只能注册会员观看，你传入verify登录后看看

**Comment by mz289** [comment]
验证登录后还是无法获取播放链接

**Comment by Passkou** [comment]
这个我也不知道是怎么回事了，有的视频获取不到也很迷，一直提示权限不足，可能是b站限制了吧

**Comment by mz289** [comment]
看了一下源码发现get_video_info()没有传cookies给Get类
我试了一下[bilibili_video_download_v2.py](https://github.com/Henryhaohao/Bilibili_video_download/blob/master/bilibili_video_download_v2.py)这个项目发现用https://api.bilibili.com/x/player/playurl 这个api也可以获取高清视频地址好像要加一个清晰度的参数，用这个应该api也可以解决无法获取会员视频地址的问题

**Comment by Passkou** [comment]
v1.3.0传进去了，b站的视频标识机制也变了，具体的看更新日志
