### ISSUE TITLE
@danmaku.on()可以在类中使用吗？应该如何使用？

### ISSUE THREAD

**Issue by a08381** [Passkou/bilibili_api#41]
想用类区分一下监听不同的房间，不知道此处开头的self会不会影响到数据传递？

**Comment by Passkou** [comment]
可以，直接用就行，self是特殊参数不会影响的
@dm.on('xxxx')
def func(self, event):
   pass

**Comment by a08381** [comment]
那这个类中的connect方法是不会调用之后继续往下跑，而是要等到ws断开吗？

**Comment by Passkou** [comment]
会阻塞，如果不想阻塞可以用多线程

**Comment by a08381** [comment]
> 可以，直接用就行，self是特殊参数不会影响的
> @dm.on('xxxx')
> def func(self, event):
> pass

实测是有问题的。

```python
    @danmaku.on("DANMU_MSG")
    def on_receive(self, *args, **kwargs):
        self.danmaku.logger.debug("触发了on_receive")
        for a in args:
            print(f"args: <{type(a)}> {a}")
        for (k, v) in kwargs:
            print(f"<{type(k)}> {k} = <{type(v)}> {v}")
        # data = args[0]
        # info = data["info"]
        # username = info[2][1]
        # message = info[1]
        # self.danmaku.logger.info(f"{username}: {message}")
```

log
```
[2020-09-10 18:28:41,567][DEBUG] 正在获取真实房间号
Running on http://127.0.0.1:5000 (CTRL + C to quit)
[2020-09-10 18:28:41,750][DEBUG] 获取成功，真实房间号：33156
[2020-09-10 18:28:41,756][DEBUG] 正在获取聊天服务器配置
[2020-09-10 18:28:41,906][DEBUG] 聊天服务器配置获取成功
[2020-09-10 18:28:41,910][DEBUG] 准备连接直播间
[2020-09-10 18:28:41,910][DEBUG] 正在尝试连接主机： wss://tx-gz-live-comet-01.chat.bilibili.com:443/sub
[2020-09-10 18:28:42,074][DEBUG] 连接主机成功, 准备发送认证信息
[2020-09-10 18:28:42,076][DEBUG] 发送心跳包
[2020-09-10 18:28:42,093][DEBUG] 收到信息：[{'protocol_version': 1, 'datapack_type': 8, 'data': {'code': 0}}]
[2020-09-10 18:28:42,094][INFO] 连接服务器并认证成功
[2020-09-10 18:28:42,109][DEBUG] 收到信息：[{'protocol_version': 1, 'datapack_type': 3, 'data': {'view': 11}}]
[2020-09-10 18:28:42,110][DEBUG] 收到心跳包反馈
[2020-09-10 18:28:42,495] Running on 127.0.0.1:5000 over http (CTRL + C to quit)
[2020-09-10 18:28:50,953][DEBUG] 收到信息：[{'protocol_version': 0, 'datapack_type': 5, 'data': {'cmd': 'NOTICE_MSG', 'full': {'head_icon': 'http://i0.hdslb.com/bfs/live/b29add66421580c3e680d784a827202e512a40a0.webp', 'tail_icon': 'http://i0.hdslb.com/bfs/live/822da481fdaba986d738db5d8fd469ffa95a8fa1.webp', 'head_icon_fa': 'http://i0.hdslb.com/bfs/live/49869a52d6225a3e70bbf1f4da63f199a95384b2.png', 'tail_icon_fa': 'http://i0.hdslb.com/bfs/live/38cb2a9f1209b16c0f15162b0b553e3b28d9f16f.png',
'head_icon_fan': 24, 'tail_icon_fan': 4, 'background': '#66A74EFF', 'color': '#FFFFFFFF', 'highlight': '#FDFF2FFF', 'time': 20}, 'half': {'head_icon': 'http://i0.hdslb.com/bfs/live/ec9b374caec5bd84898f3780a10189be96b86d4e.png', 'tail_icon': '', 'background': '#85B971FF', 'color': '#FFFFFFFF', 'highlight': '#FDFF2FFF', 'time': 15}, 'side': {'head_icon': '', 'background': '', 'color': '', 'highlight': '', 'border': ''}, 'roomid': 21749031, 'real_roomid': 21749031, 'msg_common': '<%蓬山木Channel%>投喂<%紗耶_sayako%>1个小电视飞船，点击前往TA的房间吧！', 'msg_self': '<%蓬山木Channel%>投喂<%紗耶_sayako%>1个小电视飞船，快来围观吧！', 'link_url': 'https://live.bilibili.com/21749031?from=28003&extra_jump_from=28003&live_lottery_type=1&broadcast_type=1', 'msg_type': 2, 'shield_uid': -1, 'business_id': '25'}}]
[2020-09-10 18:28:51,170][DEBUG] 收到信息：[{'protocol_version': 0, 'datapack_type': 5, 'data': {'cmd': 'DANMU_MSG', 'info': [[0, 1, 25, 16777215, 1599733732104, 811288984, 0, '61d884cf', 0, 0, 0, ''], '弹幕测试', [623906, '风之哀是个咕咕怪', 0, 0, 0, 10000, 1, ''], [5, '布丁', '布哥-BOOG', 15426, 5805790, '', 0, 5805790, 5805790, 5805790, 0, 1, 7243615], [33, 0, 10512625, '>50000'], ['title-127-1', 'title-127-1'], 0, 0, None, {'ts': 1599733732, 'ct': 'D37E1FA0'}, 0, 0, None, None, 0]}}]
Future exception was never retrieved
future: <Future finished exception=AttributeError("'dict' object has no attribute 'danmaku'")>
Traceback (most recent call last):
  File "c:\users\office02\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\360Downloads\NeteaseMusic_Live_on_Bilibili\live\room.py", line 39, in on_receive
    self.danmaku.logger.debug("触发了on_receive")
AttributeError: 'dict' object has no attribute 'danmaku'
[2020-09-10 18:29:12,072][DEBUG] 发送心跳包
```

**Comment by Passkou** [comment]
类未被实例化，但是装饰器代码却当做方法处理了，就造成了报错。
解决方法是先更新API到2.1.0版本，然后使用以下代码：
```python
import bilibili_api

room = bilibili_api.live.LiveDanmaku(20, debug=True)


class Test:
    def __init__(self):
        room.add_event_handler("ALL", self.method)

    def method(self, event):
        print(event)


test = Test()


if __name__ == '__main__':
    room.connect()
```
`add_event_handler`的具体用法参照开发文档

**Comment by a08381** [comment]
> 类未被实例化，但是装饰器代码却当做方法处理了，就造成了报错。
> 解决方法是先更新API到2.1.0版本，然后使用以下代码：
> 
> ```python
> import bilibili_api
> 
> room = bilibili_api.live.LiveDanmaku(20, debug=True)
> 
> 
> class Test:
>     def __init__(self):
>         room.add_event_handler("ALL", self.method)
> 
>     def method(self, event):
>         print(event)
> 
> 
> test = Test()
> 
> 
> if __name__ == '__main__':
>     room.connect()
> ```
> 
> `add_event_handler`的具体用法参照开发文档

我觉得不是这个问题。。。

不过新版本确实解决了我的问题

贴上我的完整代码
```python
from bilibili_api import Danmaku, Verify, live
from threading import Thread

from live.settings import settings


class Live(live.LiveDanmaku):

    def __init__(self, room_display_id, debug=False, use_wss=True, verify=None):
        super().__init__(room_display_id, debug=debug, use_wss=use_wss, verify=verify)

    def register(self, event: str, func: callable):
        self.__getattribute__("_LiveDanmaku__event_handlers")[event].append(func)


class Room:

    verify = settings.verify
    danmaku = Live(settings.room_id, debug=True, verify=verify)

    def __init__(self):
        self.connected = False
        self.danmaku.register("DANMU_MSG", self.on_receive)

    def connect(self):
        if not self.connected:
            self.connected = True
            self.threading = Connect(self)
            self.threading.start()

    def disconnect(self):
        if self.connected:
            self.connected = False
            self.danmaku.disconnect()
            self.threading.join()

    def reconnect(self):
        self.disconnect()
        self.connect()

    def send(self, text: str):
        danmaku = Danmaku(text=text)
        live.send_danmaku(self.danmaku.room_id, danmaku, verify=self.verify)

    # @danmaku.on("DANMU_MSG")
    def on_receive(self, *args, **kwargs):
        self.danmaku.logger.debug("触发了on_receive")
        for a in args:
            print(f"args: <{type(a)}> {a}")
        for (k, v) in kwargs:
            print(f"<{type(k)}> {k} = <{type(v)}> {v}")
        # data = args[0]
        # info = data["info"]
        # username = info[2][1]
        # message = info[1]
        # self.danmaku.logger.info(f"{username}: {message}")


class Connect(Thread):

    def __init__(self, room: Room):
        super().__init__()
        self.room = room
        self.daemon = True

    def run(self):
        while self.room.connected:
            self.room.danmaku.connect()

```

**Comment by a08381** [comment]
> 解决问题就行了，新版现在自带功能监控多个房间了，用异步的，可以参考一下开发文档

异步也是这次才加上的吧？我记得之前是不能给监听方法加async字段的

**Comment by Passkou** [comment]
是的，新版本加上的

**Comment by a08381** [comment]
遇到了新的问题

更新后的代码不可以直接使用了

提示
```
There is no current event loop in thread 'Thread-1'
```

手动修复后disconnect似乎失效

代码：https://paste.ubuntu.com/p/fBHxxcfjgg/

测试代码：
```python
if __name__ == "__main__":
    room = Room()
    room.connect()

    time.sleep(10)

    room.disconnect()

    Application.run()
```

**Comment by a08381** [comment]
思考是否有必要将我自行创建的这个loop传递给quart

**Comment by a08381** [comment]
我觉得按我的业务逻辑一般不会遇到这种问题，应该没事
