### ISSUE TITLE
【提问】LiveDanmaku连接时出错

### ISSUE THREAD

**Issue by Reina-a** [Passkou/bilibili_api#56]
基本按照文档的调用方法

```py
from bilibili_api.live import LiveDanmaku
from bilibili_api import Verify

veri = Verify('xxxxxx', 'xxxxxxx')
danmu = LiveDanmaku(room_display_id=xxxxx, debug=True, verify=veri)
@danmu.on("DANMU_MSG")
async def on_danmu(msg):
    print(msg)

if __name__ == "__main__":
    danmu.connect()
```
因为打开了debug， debug信息如下

```
正在获取真实房间号
获取成功，真实房间号：xxxx
正在获取聊天服务器配置
聊天服务器配置获取成功
准备连接直播间
正在尝试连接主机： wss://tx-gz-live-comet-03.chat.bilibili.com:443/sub
连接主机成功, 准备发送认证信息
```
紧接着就出错了， 具体的Traceback如下：
```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    danmu.connect()
  File "/home/reina/.local/lib/python3.6/site-packages/bilibili_api/live.py", line 403, in connect
    loop.run_until_complete(self.__main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/reina/.local/lib/python3.6/site-packages/bilibili_api/live.py", line 444, in __main
    await self.__loop()
  File "/home/reina/.local/lib/python3.6/site-packages/bilibili_api/live.py", line 456, in __loop
    asyncio.create_task(self.__heartbeat())
AttributeError: module 'asyncio' has no attribute 'create_task'
```

请问该如何解决？

顺带一提， 好像现在直播房间的real_id和display_id一样了（不大确定）

如果能解答的话就太感谢了！

**Comment by Passkou** [comment]
请升级python3.8，你的是3.6，协程功能好像是3.7之后有的，升级后应该就没问题了

**Comment by oodzfa** [comment]
python3.7和3.8有什么差别？

**Comment by jingyuexing** [comment]
> 请升级python3.8，你的是3.6，asyncio好像是3.7之后加了新功能，我的开发环境是3.8，升级后应该就没问题了。
> 另外一些签约主播b站会给个简短的房间号(display_id)，其他普通主播display_id和real_id是一样的

感觉还是环境稳定好些,或者申明下库的Python版本
