### ISSUE TITLE
在尝试获取视频的评论的时候出现了网络错误，错误代码是412

### ISSUE THREAD

**Issue by capjie** [Passkou/bilibili_api#58]
类型：提问
版本：2.1.4
使用的Python版本：3.7.7

**先给老哥点个赞👍。**
10月9号晚上的时候，在使用中get_comments函数爬取评论的时候遇到了网络错误，错误代码412的问题。之前没遇到过，这是B站的问题么？
```
Traceback (most recent call last):
  File "d:/专业综合实训/test.py", line 3, in <module>
    text = video.get_comments(bvid=Bvid)
  File "D:\python37\lib\site-packages\bilibili_api\video.py", line 486, in get_comments
    replies = common.get_comments(aid, "video", order, limit, callback, verify)
  File "D:\python37\lib\site-packages\bilibili_api\common.py", line 171, in get_comments
    resp = get_comments_raw(oid=oid, pn=page, order=order, verify=verify, type_=type_)
  File "D:\python37\lib\site-packages\bilibili_api\common.py", line 148, in get_comments_raw
    resp = utils.get(api["url"], params=params, cookies=verify.get_cookies())
  File "D:\python37\lib\site-packages\bilibili_api\utils.py", line 400, in get
    resp = request("GET", url=url, params=params, cookies=cookies, headers=headers, **kwargs)
  File "D:\python37\lib\site-packages\bilibili_api\utils.py", line 387, in request
    raise exceptions.NetworkException(req.status_code)
bilibili_api.exceptions.NetworkException: 网络错误。状态码：412
```

**Comment by Passkou** [comment]
请求速度过快会被屏蔽的，你看看正常打开网页视频评论还能加载出来吗，如果加载不出就是被屏蔽了

**Comment by tuyurong** [comment]
胸dei，你这个爬评论的代码是怎么写的呀，可以分享一下吗
