### ISSUE TITLE
LiveDanmaku的表现似乎不太正常

### ISSUE THREAD

**Issue by a08381** [Passkou/bilibili_api#81]
在connect阻塞状态下使用disconnect会导致报错。

报错：

```
Traceback (most recent call last):
  File "d:/Download/bilibili_api/example.py", line 33, in <module>
    live_danmaku.connect()
  File "d:\Download\bilibili_api\bilibili_api\live.py", line 405, in connect
    asyncio.get_event_loop().run_until_complete(self.__main())
  File "c:\users\administrator\.pyenv\pyenv-win\versions\3.8.6\lib\asyncio\base_events.py", line 614, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```

以及类型中获取了一个event loop，但是看上去并没有使用。

**Comment by a08381** [comment]
我好像调明白了，这样写应该是正确的？

```python
import asyncio

from bilibili_api.live import LiveDanmaku


async def connect(danmaku: LiveDanmaku):
    await asyncio.ensure_future(danmaku.connect(True))


async def reconnect(danmaku: LiveDanmaku):
    await asyncio.sleep(20)
    danmaku.disconnect()
    await asyncio.ensure_future(danmaku.connect(True))


if __name__ == "__main__":
    live_danmaku = LiveDanmaku(33156, debug=True)
    loop = asyncio.get_event_loop()
    asyncio.gather(connect(live_danmaku), reconnect(live_danmaku), loop=loop)
    loop.run_forever()
```

测试好像这样写在reconnect之后没有出现奇怪的问题，也没有使用多线程
