### ISSUE TITLE
get_channel_info_by_tid()方法因channel.json中部分分区没有tid属性导致出错“KeyError: 'tid'”

### ISSUE THREAD

**Issue by imldy** [Passkou/bilibili_api#97]
`channel.get_channel_info_by_tid()`方法因`channel.json`中部分子分区没有`tid`属性导致出错

```
Traceback (most recent call last):
  File "D:/PycharmProjects/bilibili_Test/channelT.py", line 6, in <module>
    res = channel.get_channel_info_by_tid(21)
  File "D:\Develop_Tools\Python\Python38\lib\site-packages\bilibili_api\channel.py", line 33, in get_channel_info_by_tid
    if tid == sub_ch["tid"]:
KeyError: 'tid'
```
![image](https://user-images.githubusercontent.com/53949747/103442236-5977f480-4c8f-11eb-89c5-8082daf0c765.png)

**Comment by Passkou** [comment]
试试测试版：https://github.com/Passkou/bilibili_api/releases/tag/3.1.7b0

**Comment by Passkou** [comment]
3.1.7 已解决
